apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: java-spring-pod-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        name: java-spring-pod-label
    spec:
      volumes:
        - name: secretvolume 
          imagePullSecrets:
            secretName: ecr
      containers:
        - name: java-spring
          image: <ECR_IMAGE>
          ports:
            - containerPort: 8080
      imagePullSecrets:
      - name: ecr