name: Java Spring CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-java-spring:

    runs-on: ubuntu-latest 
    # using ubuntu-latest because docker is pre installed.
    
    steps:
      - name: Checkout
        run: |
            sudo git clone https://${{secrets.USERNAME}}:${{secrets.SECRET}}@github.com/${{secrets.USERNAME}}/${{secrets.REPOSITORY}}.git /${{secrets.REPOSITORY}}

      - name: Build
        run: |
            docker run --rm \
                -p 9000:9000 \
                -v sonarqube_extensions:/opt/sonarqube/extensions \
                sonarqube
            sudo docker build -t spring-app --build-arg SECRET=${{secrets.SECRET}} --build-arg USERNAME=${{secrets.USERNAME}} --build-arg REPOSITORY=${{secrets.REPOSITORY}} /${{secrets.REPOSITORY}}

      - name: Push to ECR
        run: |
            echo "Pushing to ECR"

      - name: Deploy
        run: |
            echo "Deploying to ECR"