name: Java Spring CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-java-spring:

    runs-on: ubuntu-latest 
    # using ubuntu-latest because docker is pre installed.
    
    steps:
      - name: Checkout
        run: |
            sudo git clone https://${{secrets.USERNAME}}:${{secrets.SECRET}}@github.com/${{secrets.USERNAME}}/${{secrets.REPOSITORY}}.git /${{secrets.REPOSITORY}}

      - name: Build, Test, Lint
        run: |
            sudo docker build -t spring-app --build-arg SECRET=${{secrets.SECRET}} --build-arg USERNAME=${{secrets.USERNAME}} --build-arg REPOSITORY=${{secrets.REPOSITORY}} /${{secrets.REPOSITORY}}

      - name: Push to ECR
        run: |
            aws ecr get-login-password --region ${{secrets.ECR_REGION}} | docker login -u AWS -p ${{secrets.ECR_SECRET}} ${{secrets.ECR_URI}}
            docker tag ${{secrets.IMAGE_NAME}}:${{ github.run_number}} ${{secrets.ECR_URI}}
            docker push ${{secrets.ECR_URI}}

      - name: Deploy
        run: |
            echo "Deploying to ECR"