name: Java Spring CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest 
    # using ubuntu-latest because docker is pre installed.
    
    steps:
    - name: Checkout
      run: |
      echo "Hello World!"

    - name: Build, Test, Lint
      run: |
      docker run -d --name sonarqube \
        --network=bridge \
        -p 9000:9000 \
        -e SONAR_JDBC_USERNAME=${{USERNAME}} \
        -e SONAR_JDBC_PASSWORD=${{SECRET}}\
        -v sonarqube_data:/opt/sonarqube/data \
        -v sonarqube_extensions:/opt/sonarqube/extensions \
        -v sonarqube_logs:/opt/sonarqube/logs \
        sonarqube:community
      docker build -t spring-app --build-arg SECRET=${{SECRET}} --build-arg USERNAME=${{USERNAME}} --build-arg REPOSITORY=${{REPOSITORY}} /app

    - name: Pust to ECR
      run: |
      echo "Pushing to ECR"

    - name: Deploy
      run: |
      echo "Deploying to ECR"