name: Java Spring CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-java-spring:

    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        run: |
            sudo git clone https://${{secrets.USERNAME}}:${{secrets.SECRET}}@github.com/${{secrets.USERNAME}}/${{secrets.REPOSITORY}}.git /${{secrets.REPOSITORY}}

      - name: Build, Test, Lint
        run: |
            sudo docker build -t spring-app --build-arg SECRET=${{secrets.SECRET}} --build-arg USERNAME=${{secrets.USERNAME}} --build-arg REPOSITORY=${{secrets.REPOSITORY}} /${{secrets.REPOSITORY}}

      - name: Push to ECR
        run: |
            aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}
            sudo echo aws_secret_access_key=${{secrets.AWS_SECRET_ACCESS_KEY}} >> ~/.aws/credentials
            aws ecr get-login-password --region ${{secrets.ECR_REGION}} | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.ECR_REGION}}.amazonaws.com    
            docker tag ${{secrets.IMAGE_NAME}} ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.ECR_REGION}}.amazonaws.com/${{secrets.IMAGE_NAME}}:${{github.run_number}}                            
            docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.ECR_REGION}}.amazonaws.com/${{secrets.IMAGE_NAME}}:${{github.run_number}}

      - name: Deploy
        run: |
            sudo mkdir ~/.kube
            sudo echo ${{secrets.KUBERNETES_CONFIG}} >> config
            sudo mv config ~/.kube/
            sed -i "s|<ECR_IMAGE>|${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.ECR_REGION}}.amazonaws.com/${{secrets.IMAGE_NAME}}:${{github.run_number}}|" /${{secrets.REPOSITORY}}/kubernetes/deployment.yaml
            kubectl apply -f /${{secrets.REPOSITORY}}/kubernetes/deployment.yaml -f /${{secrets.REPOSITORY}}/kubernetes/service.yaml
